### ISSUE TITLE
crates.io Package

### ISSUE THREAD

**Issue by benjhar** [benjhar/osc#1]
Hi @JamesHallowell,

I've written up this library as a part of some work with a freelance client, this part they agreed should be open-sourced. I'll be writing test cases and an OSC server implementation in the next coming days. I thought it might be a good idea to contact you and ask about using the name "osc" to publish on crates.io, to avoid name duplication.
If you're not in a position to transfer the name that's alright, I thought I should ask just in case.

Won't be looking to publish on crates.io for the next couple days, wanted to give you some time to log onto GitHub + see the notification!

**Comment by JamesHallowell** [comment]
Hi @benjhar, I'm not planning on using that crate name any more so I'll transfer it over to you!

**Comment by benjhar** [comment]
Thanks!
